// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9fRag-2IelsYeYHl0sDz5d02HOc7E3Q8',
    appId: '1:1055095032779:web:5b05361b24de0f8587844e',
    messagingSenderId: '1055095032779',
    projectId: 'dalily-56933',
    authDomain: 'dalily-56933.firebaseapp.com',
    storageBucket: 'dalily-56933.appspot.com',
    measurementId: 'G-CFDBL8EN01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp97RQn2CaZGA3W9Xdx9uxwLx9O9QeTEg',
    appId: '1:1055095032779:android:0c0cccf511cf125287844e',
    messagingSenderId: '1055095032779',
    projectId: 'dalily-56933',
    storageBucket: 'dalily-56933.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjVkqxg2bGV3_i7i4hdv1wRLkZCHZ6DXQ',
    appId: '1:1055095032779:ios:b88a25a0789d898387844e',
    messagingSenderId: '1055095032779',
    projectId: 'dalily-56933',
    storageBucket: 'dalily-56933.appspot.com',
    iosClientId:
        '1055095032779-kmk3itg6oth452u8v6sjlbqbm9rlpcmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.dalily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjVkqxg2bGV3_i7i4hdv1wRLkZCHZ6DXQ',
    appId: '1:1055095032779:ios:b88a25a0789d898387844e',
    messagingSenderId: '1055095032779',
    projectId: 'dalily-56933',
    storageBucket: 'dalily-56933.appspot.com',
    iosClientId:
        '1055095032779-kmk3itg6oth452u8v6sjlbqbm9rlpcmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.dalily',
  );
}
